Query ip
jeelabs/esp-link pull request #289
Opened 2017-05-27 15:44 UTC by dannybackx

Minimal testing performed :-)

This goes with a PR for el-client that I need to create too.

Functionality provided with this PR is best summarized by the additional codes in cmd/cmd.h : 
+  CMD_GET_WIFI_INFO,   // query ip address info
+  CMD_SET_WIFI_INFO,   // set ip address info
+  CMD_WIFI_GET_APCOUNT = 50,    // Get number of access points
+  CMD_WIFI_GET_APNAME,     // Get the name (ssid) of an access point
+  CMD_WIFI_SELECT_SSID,     // select a network to connect to
+  CMD_WIFI_SIGNAL_STRENGTH,    // Query RSSI (wifi signal strength)
+  CMD_WIFI_GET_SSID,           // Query SSID/network name currently connected to
+  CMD_WIFI_START_SCAN,         // Trigger a scan (takes a long time)

2017-05-31 04:50 UTC, tve requested changes
Looking nice overall! I made a slew of minor comments.

2017-05-31 04:50 UTC, tve commented on cmd/handlers.c
> +  os_printf("WifiGetApCount : %d\n", n);
The `os_printf` in this file need to be converted to `DBG` so they can be disabled. See 8 lines up, for example.

2017-05-31 04:50 UTC, tve commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+2);
Shouldn't that be len+1 ?

2017-05-31 04:50 UTC, tve commented on cmd/handlers.c
> +static void ICACHE_FLASH_ATTR cmdSetWifiInfo(CmdPacket *cmd) {
unimplemented? then remove for now?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiservices.c
> +#include "cmd.h"
why is this needed?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +// Start scanning, API interface
Can you consolidate the code a bit and have one function call the other? Flash isn't infinite...

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +  os_printf("AP %s\n", cgiWifiAps.apData[i]->ssid);
DBG or delete...

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +// Danny
unimplemented -> remove for now?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +ICACHE_FLASH_ATTR void wifiGetApName(int i, char *ptr) {
Add a comment for the function?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +ICACHE_FLASH_ATTR int wifiSignalStrength(int i) {
Add a comment for the function?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +void ICACHE_FLASH_ATTR cmdWifiQuerySSID(CmdPacket *cmd) {
This should be in handlers.c not here...

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +  // bool res = wifi_station_get_config(&conf);
???

2017-05-31 04:50 UTC, tve commented on cmd/handlers.c
> +static void ICACHE_FLASH_ATTR cmdWifiSignalStrength(CmdPacket *cmd) {
Add a comment for the function?

2017-05-31 04:50 UTC, tve commented on esp-link/status.c
> +#include "cmd.h"
Why is this needed?

2017-05-31 04:50 UTC, tve commented on esp-link/mqtt_client.c
> +void ICACHE_FLASH_ATTR cmdMqttGetClientId(CmdPacket *cmd) {
Should be in handlers.c?

2017-05-31 04:50 UTC, tve commented on esp-link/mqtt_client.c
> +#include "cmd/cmd.h"
This should be included here.

2017-05-31 04:50 UTC, tve commented on esp-link/main.c
> +#include "cmd.h"
This shouldn't be needed here?

2017-05-31 04:50 UTC, tve commented on esp-link/cgiwifi.c
> +#include "cmd.h"
This shouldn't be included here...

2017-05-31 16:17 UTC, dannybackx commented
On 05/31/2017 06:50 AM, Thorsten von Eicken wrote:
> In esp-link/cgiservices.c <https://github.com/jeelabs/esp-link/pull/289#discussion_r119269617>:
> > @@ -1,4 +1,5 @@
>   #include <esp8266.h>
> +#include "cmd.h"
>
> why is this needed?
>

If I remove it, I get
 > CC esp-link/cgiservices.c
 > In file included from esp-link/cgiservices.c:2:0:
 > esp-link/cgiwifi.h:31:23: error: unknown type name 'CmdPacket'
 >  void cmdWifiQuerySSID(CmdPacket *cmd);
 >                        ^
 > esp-link/cgiwifi.h:32:23: error: unknown type name 'CmdPacket'
 >  void cmdWifiStartScan(CmdPacket *cmd);
 >                        ^
 > Makefile:521: recipe for target 'build/esp-link/cgiservices.o' failed

Or is this an error in my build environment ?

     Danny


-- 
Danny Backx - danny.backx@scarlet.be - http://danny.backx.info

2017-06-16 03:35 UTC, tve commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+1);
where is this ever freed? it looks like a heap allocation is totally unnecessary...

2017-06-16 03:35 UTC, tve commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+2);
where is this ever freed?

2017-06-16 03:35 UTC, tve commented on cmd/handlers.c
> +    ssid = os_malloc(len+1);
where is this ever freed?

2017-06-16 03:36 UTC, merged

2017-06-16 03:36 UTC, tve commented
Thanks much!

2017-06-17 05:31 UTC, dannybackx commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+1);
Just committed a fix

2017-06-17 05:31 UTC, dannybackx commented on cmd/handlers.c
> +    ssid = os_malloc(len+1);
Just committed a fix

2017-06-17 05:31 UTC, dannybackx commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+1);
Just committed a fix

2017-06-17 14:35 UTC, tve commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+1);
oops, sorry, after writing the comments I decided to merge your commit and fix the issues myself. It's already all on master :-) (No guarantees that it builds or works, I had to go to bed...)

2017-06-17 15:52 UTC, dannybackx commented on cmd/handlers.c
> +    pass = (char *)os_malloc(len+1);
No problem, I only spent a few minutes on it. Short enough not to notice that you'd already done it.
I'll check the build.